"""runtime config and feed poll state

Two tables discovery needs: the knobs it reads its cadence from, and what it remembers about
each feed between polls.

``feed_poll_state`` is separate from ``feed`` on purpose. ``feed.updated_at`` is trigger-
maintained and is the version token every compare-and-set write on the registry compares
against, so a poller writing an ETag onto that row every cycle would move the token every
cycle and make every admin edit fail with a conflict.

The ``runtime_config`` trigger is added by hand below. Neither it nor its function is visible
to ``Base.metadata``, so autogenerate will not propose them and ``alembic check`` cannot see
them drift — mirrors source_touch_updated_at() and feed_touch_updated_at().

⚠️ The seeded value below duplicates the default declared on ``IntKnob`` in
``meridian.db.runtime_config``, because a migration must not import application code. The two
are held together by a test, not by the type system.

Revision ID: 18b6d260b90e
Revises: a3b46d0891f8
Create Date: 2026-08-25 17:08:46.063154

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18b6d260b90e"
down_revision: str | Sequence[str] | None = "a3b46d0891f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_config",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_runtime_config")),
    )
    op.create_table(
        "feed_poll_state",
        sa.Column("feed_id", sa.BigInteger(), nullable=False),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column(
            "last_polled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.feed_id"],
            name=op.f("fk_feed_poll_state_feed_id_feed"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("feed_id", name=op.f("pk_feed_poll_state")),
    )
    # ### end Alembic commands ###

    # runtime_config.updated_at is the version token every compare-and-set write on a knob
    # compares against, and the emergency path is a psql session — a token the ORM maintained
    # would not move for a hand-written UPDATE, and the next admin write would silently apply
    # on top of it. Mirrors source_touch_updated_at().
    op.execute(
        """
        CREATE FUNCTION runtime_config_touch_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER runtime_config_set_updated_at
        BEFORE UPDATE ON runtime_config
        FOR EACH ROW EXECUTE FUNCTION runtime_config_touch_updated_at()
        """
    )

    # Seeded so the key always has a row: every write is then an update against a version
    # token, with no second path for creating one. 300 s is the 5-minute discovery allocation
    # in the freshness budget (RFC §7.1).
    op.execute(
        """
        INSERT INTO runtime_config (key, value)
        VALUES ('poll_interval_seconds', '300')
        ON CONFLICT (key) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feed_poll_state")
    op.execute("DROP TRIGGER IF EXISTS runtime_config_set_updated_at ON runtime_config")
    op.execute("DROP FUNCTION IF EXISTS runtime_config_touch_updated_at()")
    op.drop_table("runtime_config")
    # ### end Alembic commands ###
