"""canonical data model

Revision ID: 1451971dd5f4
Revises:
Create Date: 2026-08-12 15:02:35.047454

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1451971dd5f4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster",
        sa.Column("cluster_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("representative_topic", sa.Text(), nullable=True),
        sa.Column("topic_margin", sa.Float(), nullable=True),
        sa.Column("article_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("distinct_source_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("earliest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_status", sa.String(length=7), server_default="open", nullable=False),
        sa.CheckConstraint(
            "window_status IN ('open', 'evicted')", name=op.f("ck_cluster_window_status")
        ),
        sa.PrimaryKeyConstraint("cluster_id", name=op.f("pk_cluster")),
    )
    op.create_index("ix_cluster_window_status", "cluster", ["window_status"], unique=False)
    op.create_table(
        "source",
        sa.Column("source_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("home_url", sa.Text(), nullable=False),
        sa.Column("discovery_method", sa.String(length=14), nullable=False),
        sa.Column("acquisition_tier", sa.String(length=15), nullable=False),
        sa.Column("rights_level", sa.String(length=13), nullable=False),
        sa.Column("jurisdiction", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("rate_limit_per_min", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "acquisition_tier IN ('1_full_feed', '2_publisher_api', '3_extraction')",
            name=op.f("ck_source_acquisition_tier"),
        ),
        sa.CheckConstraint(
            "discovery_method IN ('rss', 'sitemap', 'websub', 'section_scrape')",
            name=op.f("ck_source_discovery_method"),
        ),
        sa.CheckConstraint(
            "rights_level IN ('body_text', 'headline_only')", name=op.f("ck_source_rights_level")
        ),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_source")),
    )
    op.create_table(
        "canonical_record",
        sa.Column("article_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("url_canonical", sa.Text(), nullable=False),
        sa.Column("guid", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("lede", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("body_provenance", sa.String(length=15), nullable=True),
        sa.Column("has_body_rights", sa.Boolean(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "pipeline_state", sa.String(length=10), server_default="discovered", nullable=False
        ),
        sa.Column("terminal_reason", sa.String(length=16), nullable=True),
        sa.CheckConstraint(
            "body_provenance IN ('tier1_feed', 'tier2_api', 'tier3_extracted')",
            name=op.f("ck_canonical_record_body_provenance"),
        ),
        sa.CheckConstraint(
            "pipeline_state IN ('discovered', 'acquired', 'classified', 'clustered')",
            name=op.f("ck_canonical_record_pipeline_state"),
        ),
        sa.CheckConstraint(
            "terminal_reason IN ('failed', 'dropped_language')",
            name=op.f("ck_canonical_record_terminal_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.source_id"],
            name=op.f("fk_canonical_record_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("article_id", name=op.f("pk_canonical_record")),
        sa.UniqueConstraint("source_id", "guid", name=op.f("uq_canonical_record_source_id_guid")),
        sa.UniqueConstraint("url_canonical", name=op.f("uq_canonical_record_url_canonical")),
    )
    op.create_index(
        "ix_canonical_record_content_hash", "canonical_record", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_canonical_record_pipeline_state", "canonical_record", ["pipeline_state"], unique=False
    )
    op.create_table(
        "summary",
        sa.Column("cluster_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("faithfulness_score", sa.Float(), nullable=True),
        sa.Column("withheld", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("withhold_reason", sa.String(length=22), server_default="none", nullable=False),
        sa.Column("provenance_urls", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "withhold_reason IN ('none', 'below_faithfulness_bar', 'rights_excluded', 'insufficient_sources')",
            name=op.f("ck_summary_withhold_reason"),
        ),
        sa.CheckConstraint(
            "(withheld IS FALSE AND withhold_reason = 'none') OR (withheld IS TRUE AND withhold_reason <> 'none' AND \"text\" IS NULL)",
            name=op.f("ck_summary_withheld_matches_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.cluster_id"],
            name=op.f("fk_summary_cluster_id_cluster"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cluster_id", name=op.f("pk_summary")),
    )
    op.create_table(
        "takedown",
        sa.Column("takedown_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("guid", sa.Text(), nullable=True),
        sa.Column("url_canonical", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("removed_article_id", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.String(length=14), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actioned_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scope IN ('representative', 'alternate_copy')", name=op.f("ck_takedown_scope")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.source_id"],
            name=op.f("fk_takedown_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("takedown_id", name=op.f("pk_takedown")),
    )
    op.create_index("ix_takedown_content_hash", "takedown", ["content_hash"], unique=False)
    op.create_index("ix_takedown_source_id_guid", "takedown", ["source_id", "guid"], unique=False)
    op.create_index("ix_takedown_url_canonical", "takedown", ["url_canonical"], unique=False)
    op.create_table(
        "alternate_copy",
        sa.Column("alternate_copy_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("guid", sa.Text(), nullable=True),
        sa.Column(
            "seen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["canonical_record.article_id"],
            name=op.f("fk_alternate_copy_article_id_canonical_record"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.source_id"],
            name=op.f("fk_alternate_copy_source_id_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("alternate_copy_id", name=op.f("pk_alternate_copy")),
        sa.UniqueConstraint("source_id", "guid", name=op.f("uq_alternate_copy_source_id_guid")),
        sa.UniqueConstraint("url", name=op.f("uq_alternate_copy_url")),
    )
    op.create_index("ix_alternate_copy_article_id", "alternate_copy", ["article_id"], unique=False)
    op.create_table(
        "classification",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("fallback_reason", sa.String(length=19), server_default="none", nullable=False),
        sa.Column("taxonomy_version", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "fallback_reason IN ('none', 'low_confidence', 'service_unavailable')",
            name=op.f("ck_classification_fallback_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["canonical_record.article_id"],
            name=op.f("fk_classification_article_id_canonical_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("article_id", name=op.f("pk_classification")),
    )
    op.create_table(
        "cluster_member",
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("cluster_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["canonical_record.article_id"],
            name=op.f("fk_cluster_member_article_id_canonical_record"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.cluster_id"],
            name=op.f("fk_cluster_member_cluster_id_cluster"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("article_id", name=op.f("pk_cluster_member")),
    )
    op.create_index("ix_cluster_member_cluster_id", "cluster_member", ["cluster_id"], unique=False)
    op.create_table(
        "pipeline_work",
        sa.Column("work_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column("cluster_id", sa.BigInteger(), nullable=True),
        sa.Column("stage", sa.String(length=9), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "stage IN ('acquire', 'classify', 'cluster', 'summarize')",
            name=op.f("ck_pipeline_work_stage"),
        ),
        sa.CheckConstraint(
            "(article_id IS NULL) <> (cluster_id IS NULL)",
            name=op.f("ck_pipeline_work_exactly_one_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["canonical_record.article_id"],
            name=op.f("fk_pipeline_work_article_id_canonical_record"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.cluster_id"],
            name=op.f("fk_pipeline_work_cluster_id_cluster"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("work_id", name=op.f("pk_pipeline_work")),
    )
    op.create_index(
        "ix_pipeline_work_claimable",
        "pipeline_work",
        ["stage", "next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("dead_lettered_at IS NULL"),
    )
    op.create_index(
        "uq_pipeline_work_open_article",
        "pipeline_work",
        ["article_id"],
        unique=True,
        postgresql_where=sa.text("dead_lettered_at IS NULL AND article_id IS NOT NULL"),
    )
    op.create_index(
        "uq_pipeline_work_open_cluster",
        "pipeline_work",
        ["cluster_id"],
        unique=True,
        postgresql_where=sa.text("dead_lettered_at IS NULL AND cluster_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_pipeline_work_open_cluster",
        table_name="pipeline_work",
        postgresql_where=sa.text("dead_lettered_at IS NULL AND cluster_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_pipeline_work_open_article",
        table_name="pipeline_work",
        postgresql_where=sa.text("dead_lettered_at IS NULL AND article_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_pipeline_work_claimable",
        table_name="pipeline_work",
        postgresql_where=sa.text("dead_lettered_at IS NULL"),
    )
    op.drop_table("pipeline_work")
    op.drop_index("ix_cluster_member_cluster_id", table_name="cluster_member")
    op.drop_table("cluster_member")
    op.drop_table("classification")
    op.drop_index("ix_alternate_copy_article_id", table_name="alternate_copy")
    op.drop_table("alternate_copy")
    op.drop_index("ix_takedown_url_canonical", table_name="takedown")
    op.drop_index("ix_takedown_source_id_guid", table_name="takedown")
    op.drop_index("ix_takedown_content_hash", table_name="takedown")
    op.drop_table("takedown")
    op.drop_table("summary")
    op.drop_index("ix_canonical_record_pipeline_state", table_name="canonical_record")
    op.drop_index("ix_canonical_record_content_hash", table_name="canonical_record")
    op.drop_table("canonical_record")
    op.drop_table("source")
    op.drop_index("ix_cluster_window_status", table_name="cluster")
    op.drop_table("cluster")
    # ### end Alembic commands ###
