"""read model projection

Revision ID: c13e672c1a9b
Revises: 11f4a2bfd43e
Create Date: 2026-08-26 22:47:31.917794

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c13e672c1a9b"
down_revision: str | Sequence[str] | None = "11f4a2bfd43e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_projection",
        sa.Column("cluster_id", sa.BigInteger(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("lede", sa.Text(), nullable=True),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("withhold_reason", sa.String(length=22), nullable=True),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("distinct_source_count", sa.Integer(), nullable=False),
        sa.Column("earliest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(withhold_reason IS NULL AND summary_text IS NULL) OR (withhold_reason = 'none') OR (withhold_reason <> 'none' AND summary_text IS NULL)",
            name=op.f("ck_cluster_projection_summary_matches_withhold_reason"),
        ),
        sa.CheckConstraint(
            "withhold_reason IN ('none', 'below_faithfulness_bar', 'rights_excluded', 'insufficient_sources')",
            name=op.f("ck_cluster_projection_withhold_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster.cluster_id"],
            name=op.f("fk_cluster_projection_cluster_id_cluster"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("cluster_id", name=op.f("pk_cluster_projection")),
    )
    op.create_index(
        "ix_cluster_projection_topic_latest_at",
        "cluster_projection",
        ["topic", sa.literal_column("latest_at DESC")],
        unique=False,
    )
    op.create_table(
        "cluster_projection_source",
        sa.Column("cluster_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["cluster_projection.cluster_id"],
            name=op.f("fk_cluster_projection_source_cluster_id_cluster_projection"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.source_id"],
            name=op.f("fk_cluster_projection_source_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "cluster_id", "source_id", name=op.f("pk_cluster_projection_source")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cluster_projection_source")
    op.drop_index("ix_cluster_projection_topic_latest_at", table_name="cluster_projection")
    op.drop_table("cluster_projection")
    # ### end Alembic commands ###
