"""registry timestamps; drop the article rights copy

``updated_at`` is maintained by a trigger, not by the ORM. The path this column exists to
record is an emergency one, and an emergency change to the registry is as likely to be a psql
session as a form submission; an ORM-level ``onupdate`` would silently miss exactly that case
and leave the column asserting a stale time. Neither the trigger nor its function is visible
to ``alembic check`` — nothing in ``Base.metadata`` describes them — so ``tests`` is what
holds them, not autogenerate.

Revision ID: 85d54b3a11a9
Revises: 1451971dd5f4
Create Date: 2026-08-19 12:04:06.369074

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85d54b3a11a9"
down_revision: str | Sequence[str] | None = "1451971dd5f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("canonical_record", "has_body_rights")
    op.add_column(
        "source",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "source",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION source_touch_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER source_set_updated_at
        BEFORE UPDATE ON source
        FOR EACH ROW EXECUTE FUNCTION source_touch_updated_at()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS source_set_updated_at ON source")
    op.execute("DROP FUNCTION IF EXISTS source_touch_updated_at()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source", "updated_at")
    op.drop_column("source", "created_at")
    op.add_column(
        "canonical_record",
        sa.Column("has_body_rights", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
