"""publisher and feed

A ``source`` row becomes a publisher and ``feed`` becomes what discovery polls, carrying the
URL that was absent from the model entirely. ``rate_limit_per_min`` stays on the publisher
because FR-I3 politeness is a promise about one host; ``enabled`` now exists on both tables and
means different things, an operational stop against a rotted feed URL.

``permitted_to_ingest`` is a determination read ahead of ``rights_level`` rather than a rung
within it — a terms exclusion is not a lower rung on the body_text/headline_only ladder, and
recording one as ``headline_only`` leaves the pipeline politely still polling. ``user_agent`` is
a per-publisher override because a UA carrying a contact URL is black-holed by some edges, and
it fails as a hang rather than a refusal.

⚠️ Dropping ``source.discovery_method`` and ``source.acquisition_tier`` is LOSSY and there is
deliberately no data migration. Both belong on a feed, and creating one requires a URL that does
not exist in this schema or anywhere else in the system — that absence is the reason for this
revision. A placeholder feed built from ``home_url`` was considered and rejected: no roster
source's feed is derivable from its homepage (one publisher serves its feed from a different
host and another has no usable feed at all), so the rows would be wrong in a way that reads as
configured. Re-seed the roster after upgrading.

The ``feed`` updated_at trigger is added by hand below. Neither it nor its function is visible
to ``alembic check`` — nothing in ``Base.metadata`` describes them — so the tests hold them.

Revision ID: a3b46d0891f8
Revises: 85d54b3a11a9
Create Date: 2026-08-25 14:31:56.544135

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3b46d0891f8"
down_revision: str | Sequence[str] | None = "85d54b3a11a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed",
        sa.Column("feed_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("discovery_method", sa.String(length=14), nullable=False),
        sa.Column("acquisition_tier", sa.String(length=15), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acquisition_tier IN ('1_full_feed', '2_publisher_api', '3_extraction')",
            name=op.f("ck_feed_acquisition_tier"),
        ),
        sa.CheckConstraint(
            "discovery_method IN ('rss', 'sitemap', 'websub', 'section_scrape')",
            name=op.f("ck_feed_discovery_method"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.source_id"],
            name=op.f("fk_feed_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("feed_id", name=op.f("pk_feed")),
        sa.UniqueConstraint("url", name=op.f("uq_feed_url")),
    )
    op.create_index("ix_feed_source_id", "feed", ["source_id"], unique=False)
    op.add_column("alternate_copy", sa.Column("feed_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_alternate_copy_feed_id_feed"),
        "alternate_copy",
        "feed",
        ["feed_id"],
        ["feed_id"],
        ondelete="SET NULL",
    )
    op.add_column("canonical_record", sa.Column("feed_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        op.f("fk_canonical_record_feed_id_feed"),
        "canonical_record",
        "feed",
        ["feed_id"],
        ["feed_id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "source",
        sa.Column(
            "permitted_to_ingest", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.add_column("source", sa.Column("user_agent", sa.Text(), nullable=True))
    op.drop_constraint(op.f("ck_source_acquisition_tier"), "source", type_="check")
    op.drop_constraint(op.f("ck_source_discovery_method"), "source", type_="check")
    op.drop_column("source", "acquisition_tier")
    op.drop_column("source", "discovery_method")
    # ### end Alembic commands ###
    # feed.updated_at is the version token every compare-and-set write on a feed compares
    # against, so it must move on a psql write too — an ORM-level onupdate would miss exactly
    # the emergency path the column exists to record. Mirrors source_touch_updated_at().
    op.execute(
        """
        CREATE FUNCTION feed_touch_updated_at() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER feed_set_updated_at
        BEFORE UPDATE ON feed
        FOR EACH ROW EXECUTE FUNCTION feed_touch_updated_at()
        """
    )


def downgrade() -> None:
    """Downgrade schema.

    ⚠️ The two re-added columns are filled with PLACEHOLDERS, not with recovered data. Their
    real values were dropped on the way up and live nowhere; a downgrade that refused on a
    non-empty table would instead make the schema un-rollbackable at all. They are added with a
    server default so the NOT NULL succeeds, and the default is then dropped so the resulting
    column matches what the previous revision created rather than a lookalike carrying a
    default the original never had.
    """
    op.execute("DROP TRIGGER IF EXISTS feed_set_updated_at ON feed")
    op.execute("DROP FUNCTION IF EXISTS feed_touch_updated_at()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source",
        sa.Column(
            "discovery_method",
            sa.VARCHAR(length=14),
            autoincrement=False,
            nullable=False,
            server_default="rss",
        ),
    )
    op.add_column(
        "source",
        sa.Column(
            "acquisition_tier",
            sa.VARCHAR(length=15),
            autoincrement=False,
            nullable=False,
            server_default="3_extraction",
        ),
    )
    op.alter_column("source", "discovery_method", server_default=None)
    op.alter_column("source", "acquisition_tier", server_default=None)
    op.create_check_constraint(
        op.f("ck_source_discovery_method"),
        "source",
        "discovery_method::text = ANY (ARRAY['rss'::character varying, 'sitemap'::character varying, 'websub'::character varying, 'section_scrape'::character varying]::text[])",
    )
    op.create_check_constraint(
        op.f("ck_source_acquisition_tier"),
        "source",
        "acquisition_tier::text = ANY (ARRAY['1_full_feed'::character varying, '2_publisher_api'::character varying, '3_extraction'::character varying]::text[])",
    )
    op.drop_column("source", "user_agent")
    op.drop_column("source", "permitted_to_ingest")
    op.drop_constraint(
        op.f("fk_canonical_record_feed_id_feed"), "canonical_record", type_="foreignkey"
    )
    op.drop_column("canonical_record", "feed_id")
    op.drop_constraint(op.f("fk_alternate_copy_feed_id_feed"), "alternate_copy", type_="foreignkey")
    op.drop_column("alternate_copy", "feed_id")
    op.drop_index("ix_feed_source_id", table_name="feed")
    op.drop_table("feed")
    # ### end Alembic commands ###
