"""job item provenance and length hint

Revision ID: 36044d831109
Revises: a12dc1b2b786
Create Date: 2026-08-18 21:34:03.657536

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "36044d831109"
down_revision: str | Sequence[str] | None = "a12dc1b2b786"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("summarize_job", sa.Column("max_sentences", sa.Integer(), nullable=True))
    op.add_column(
        "summarize_job_item",
        sa.Column(
            "provenance", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summarize_job_item", "provenance")
    op.drop_column("summarize_job", "max_sentences")
    # ### end Alembic commands ###
