"""platform job store

Revision ID: a12dc1b2b786
Revises:
Create Date: 2026-08-17 21:14:15.373114

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a12dc1b2b786"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summarize_job",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column("consumer", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=9), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'partial', 'failed', 'expired')",
            name=op.f("ck_summarize_job_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summarize_job")),
        sa.UniqueConstraint(
            "consumer", "idempotency_key", name=op.f("uq_summarize_job_consumer_idempotency_key")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_summarize_job_public_id")),
    )
    op.create_index(
        "ix_summarize_job_claimable",
        "summarize_job",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index("ix_summarize_job_expires_at", "summarize_job", ["expires_at"], unique=False)
    op.create_table(
        "summarize_job_item",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.String(length=255), nullable=False),
        sa.Column("documents", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("faithfulness_score", sa.Float(), nullable=True),
        sa.Column("withheld", sa.Boolean(), nullable=True),
        sa.Column("withhold_reason", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "withhold_reason IS NULL OR withhold_reason IN ('below_faithfulness_bar')",
            name=op.f("ck_summarize_job_item_withhold_reason"),
        ),
        sa.CheckConstraint(
            "faithfulness_score IS NULL OR faithfulness_score BETWEEN 0 AND 1",
            name=op.f("ck_summarize_job_item_faithfulness_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["summarize_job.id"],
            name=op.f("fk_summarize_job_item_job_id_summarize_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_summarize_job_item")),
        sa.UniqueConstraint("job_id", "item_id", name=op.f("uq_summarize_job_item_job_id_item_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summarize_job_item")
    op.drop_index("ix_summarize_job_expires_at", table_name="summarize_job")
    op.drop_index(
        "ix_summarize_job_claimable",
        table_name="summarize_job",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_table("summarize_job")
    # ### end Alembic commands ###
